# Generated by Django 3.1.6 on 2021-02-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
